### ISSUE TITLE
Only Aluminum?

### ISSUE THREAD

**Issue by lacymorrow** [dhleong/node-apple-remote#3]
Was wondering if this would work with the white remotes as well. 
They have the same buttons, I always assumed the remotes had the same internals with different skins but I don't know for sure

Anyway, I tested and it in a Meteor app and it recognizes the event but isn't setting `button` properly (`button.name` undefined).

I don't have access to an aluminum remote, so I don't know if this error is due to my remote, or another issue.

**Comment by dhleong** [comment]
I don't own any but the aluminum so I'm afraid I have no idea. I imagine it could work, but the button codes might be different. You're welcome to submit a PR that adds support if you figure it out!

**Comment by bryanberger** [comment]
It works with my white remote from circa 2011

**Comment by lacymorrow** [comment]
@decapyre - thanks so much! That indicates an issue using this package with Meteor, not an issue with the package itself.

@dhleong - thanks for developing this!

**Comment by dhleong** [comment]
No worries :)
